### PR TITLE
Add existing API routes from ocfweb

### PR DESCRIPTION
**Pull request by Kalissaac**
Brings over all the existing API routes from ocfweb
Includes `ocflib`
Fixes Dockerfile to successfully build with `ocflib`

### CODE REVIEW

**Comment by Kalissaac** [comment]
I wanted to finish bringing over all API routes before we merge it, just thought having a thread would be useful in case we run into any issues

**Comment by Kalissaac** [comment]
Turns out FastAPI doesn't have built-in caching support, so either we need to throw Redis in front of this or use a third-party library. I'm leaning towards Redis for the sake of simplicity, but not sure.

**Comment by Kalissaac** [comment]
Or maybe Python's built-in `lru_cache()`?

**Comment by Kalissaac** [comment]
So it looks like ocfweb uses Redis (through Django) so I just copied that caching over, and then we'll use `lru_cache` as well for things that need to only be computed once.

**Comment by Kalissaac** [comment]
Everything should be implemented now! I need to add the secrets to k8s for Redis and the DB, but apart from that it's all done.

**Review by ben9583 — APPROVED** [review]
Nice work! Lot of new stuff going on here; do we have tests that we run for this repo to make sure everything is working as intended?

**Comment by Kalissaac** [comment]
Yeah, that's a good point. I'll copy over some tests from ocfweb, I need to do some research on how FastAPI integrates with testing libraries

**Comment by Kalissaac** [comment]
So it looks like the only api test in ocfweb is for the desktop session tracking, all of the other tests are for other portions of the website. The issue I'm running into when making tests for the endpoints is that the data is constantly changing, and we pretty much pull everything directly from ocflib. The only other portion is the status blog announcements since we pull that in as XML and parse it to JSON. If you have suggestions on how we can test that I'm all ears.

**Pull request merged**
